language: node_js
node_js:
  - "14.17.0"
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli@12.0.0
script:
- ng lint
- ng build --prod --base-href https://jrh3k5.github.io/NicCageNovemberator/ --aot true


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/NicCageNovemberator
  on:
    branch: master